import type { SillyTavernPreset } from '../types/preset';

/** 需要校验存在的标准 marker 条目 */
export const REQUIRED_MARKERS: { id: string; name: string }[] = [
    { id: 'chatHistory',       name: 'Chat History' },
    { id: 'dialogueExamples',  name: 'Chat Examples' },
    { id: 'worldInfoBefore',   name: 'World Info (before)' },
    { id: 'worldInfoAfter',    name: 'World Info (after)' },
    { id: 'charDescription',   name: 'Char Description' },
    { id: 'charPersonality',   name: 'Char Personality' },
    { id: 'scenario',          name: 'Scenario' },
    { id: 'personaDescription', name: 'Persona Description' },
];

/**
 * 创建一个基于 SillyTavern 默认预设的空白 preset
 * 采样参数默认值来自 Default.json
 */
export function createDefaultPreset(): SillyTavernPreset {
    return {
        // 采样参数
        temperature: 1,
        frequency_penalty: 0,
        presence_penalty: 0,
        top_p: 1,
        top_k: 0,
        top_a: 0,
        min_p: 0,
        repetition_penalty: 1,
        max_context_unlocked: false,
        openai_max_context: 4095,
        openai_max_tokens: 300,
        seed: -1,

        // 内置提示词字段
        names_behavior: -1,
        send_if_empty: '',
        impersonation_prompt: '',
        new_chat_prompt: '',
        new_group_chat_prompt: '',
        new_example_chat_prompt: '',
        continue_nudge_prompt: '',
        bias_preset_selected: '',
        wi_format: '',
        scenario_format: '',
        personality_format: '',
        group_nudge_prompt: '',
        stream_openai: false,

        // 其他设置
        assistant_prefill: '',
        assistant_impersonation: '',
        use_sysprompt: false,
        squash_system_messages: false,
        media_inlining: false,
        inline_image_quality: 'low',
        continue_prefill: false,
        continue_postfix: '',
        function_calling: false,
        show_thoughts: false,
        reasoning_effort: '',
        verbosity: '',
        enable_web_search: false,
        n: 1,
        request_images: false,
        request_image_aspect_ratio: '1:1',
        request_image_resolution: '',
        extensions: {},

        // Prompts 列表（含所有标准 markers 和内置条目）
        prompts: [
            {
                name: 'Main Prompt',
                system_prompt: true,
                role: 'system',
                content: '',
                identifier: 'main',
                injection_position: 0,
                injection_depth: 0,
                forbid_overrides: false,
            },
            {
                name: 'Auxiliary Prompt',
                system_prompt: true,
                role: 'system',
                content: '',
                identifier: 'nsfw',
                injection_position: 0,
                injection_depth: 0,
                forbid_overrides: false,
            },
            {
                identifier: 'dialogueExamples',
                name: 'Chat Examples',
                system_prompt: true,
                marker: true,
                role: 'system',
                content: '',
                injection_position: 0,
                injection_depth: 0,
                forbid_overrides: false,
            },
            {
                name: 'Post-History Instructions',
                system_prompt: true,
                role: 'system',
                content: '',
                identifier: 'jailbreak',
                injection_position: 0,
                injection_depth: 0,
                forbid_overrides: false,
            },
            {
                identifier: 'chatHistory',
                name: 'Chat History',
                system_prompt: true,
                marker: true,
                role: 'system',
                content: '',
                injection_position: 0,
                injection_depth: 0,
                forbid_overrides: false,
            },
            {
                identifier: 'worldInfoAfter',
                name: 'World Info (after)',
                system_prompt: true,
                marker: true,
                role: 'system',
                content: '',
                injection_position: 0,
                injection_depth: 0,
                forbid_overrides: false,
            },
            {
                identifier: 'worldInfoBefore',
                name: 'World Info (before)',
                system_prompt: true,
                marker: true,
                role: 'system',
                content: '',
                injection_position: 0,
                injection_depth: 0,
                forbid_overrides: false,
            },
            {
                identifier: 'enhanceDefinitions',
                role: 'system',
                name: 'Enhance Definitions',
                content: '',
                system_prompt: true,
                marker: false,
                injection_position: 0,
                injection_depth: 0,
                forbid_overrides: false,
            },
            {
                identifier: 'charDescription',
                name: 'Char Description',
                system_prompt: true,
                marker: true,
                role: 'system',
                content: '',
                injection_position: 0,
                injection_depth: 0,
                forbid_overrides: false,
            },
            {
                identifier: 'charPersonality',
                name: 'Char Personality',
                system_prompt: true,
                marker: true,
                role: 'system',
                content: '',
                injection_position: 0,
                injection_depth: 0,
                forbid_overrides: false,
            },
            {
                identifier: 'scenario',
                name: 'Scenario',
                system_prompt: true,
                marker: true,
                role: 'system',
                content: '',
                injection_position: 0,
                injection_depth: 0,
                forbid_overrides: false,
            },
            {
                identifier: 'personaDescription',
                name: 'Persona Description',
                system_prompt: true,
                marker: true,
                role: 'system',
                content: '',
                injection_position: 0,
                injection_depth: 0,
                forbid_overrides: false,
            },
        ],

        // 排序（character_id 100000 和 100001，顺序与 Default.json 一致）
        prompt_order: [
            {
                character_id: 100000,
                order: [
                    { identifier: 'main', enabled: true },
                    { identifier: 'worldInfoBefore', enabled: true },
                    { identifier: 'charDescription', enabled: true },
                    { identifier: 'charPersonality', enabled: true },
                    { identifier: 'scenario', enabled: true },
                    { identifier: 'enhanceDefinitions', enabled: false },
                    { identifier: 'nsfw', enabled: true },
                    { identifier: 'worldInfoAfter', enabled: true },
                    { identifier: 'dialogueExamples', enabled: true },
                    { identifier: 'chatHistory', enabled: true },
                    { identifier: 'jailbreak', enabled: true },
                ],
            },
            {
                character_id: 100001,
                order: [
                    { identifier: 'main', enabled: true },
                    { identifier: 'worldInfoBefore', enabled: true },
                    { identifier: 'personaDescription', enabled: true },
                    { identifier: 'charDescription', enabled: true },
                    { identifier: 'charPersonality', enabled: true },
                    { identifier: 'scenario', enabled: true },
                    { identifier: 'enhanceDefinitions', enabled: false },
                    { identifier: 'nsfw', enabled: true },
                    { identifier: 'worldInfoAfter', enabled: true },
                    { identifier: 'dialogueExamples', enabled: true },
                    { identifier: 'chatHistory', enabled: true },
                    { identifier: 'jailbreak', enabled: true },
                ],
            },
        ],
    };
}
